### PR TITLE
switch to nix flake instead of shell.nix

### PR DESCRIPTION
**Pull request by silky**

### CODE REVIEW

**Review by marcosh — APPROVED** [review]
Maybe you still want a `shell.nix` which refers back to `flake.nix`, as in https://github.com/tweag/crem/blob/main/shell.nix

**Comment by silky** [comment]
interesting, with that i get:

```
11:36 am noon φ org (flake.nix +) nix-shell
error: attribute 'flake-compat' missing

       at /home/noon/dev/fix-planet/org/shell.nix:7:63:

            6|   flake-compat = fetchTarball {
            7|     url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
             |                                                               ^
            8|     sha256 = lock.nodes.flake-compat.locked.narHash;
```

**Comment by silky** [comment]
ah nevermind

**Comment by silky** [comment]
thanks @marcosh ! :)

**Pull request merged**
